{"uuid": "771df55a-9b04-4f43-a799-6f92c0883141", "children": ["06de2275-a71c-48bf-bd80-9fbc529ca182"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Service /usr/bin/safaridriver unexpectedly exited. Status code was: 1\n\n", "trace": "  File \"/Users/kris/Desktop/python_projects/Framework/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/Users/kris/Desktop/python_projects/Framework/venv/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Users/kris/Desktop/python_projects/Framework/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/kris/Desktop/python_projects/Framework/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/kris/Desktop/python_projects/Framework/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/Users/kris/Desktop/python_projects/Framework/tests/conftest.py\", line 15, in setup\n    driver = wdf.getWebDriverInstance()  # this method imported from 'WebDriverFactory' class\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/kris/Desktop/python_projects/Framework/base/webdriverfactory.py\", line 22, in getWebDriverInstance\n    driver=webdriver.Safari()\n           ^^^^^^^^^^^^^^^^^^\n  File \"/Users/kris/Desktop/python_projects/Framework/venv/lib/python3.11/site-packages/selenium/webdriver/safari/webdriver.py\", line 51, in __init__\n    self.service.start()\n  File \"/Users/kris/Desktop/python_projects/Framework/venv/lib/python3.11/site-packages/selenium/webdriver/common/service.py\", line 108, in start\n    self.assert_process_still_running()\n  File \"/Users/kris/Desktop/python_projects/Framework/venv/lib/python3.11/site-packages/selenium/webdriver/common/service.py\", line 121, in assert_process_still_running\n    raise WebDriverException(f\"Service {self._path} unexpectedly exited. Status code was: {return_code}\")\n"}, "start": 1737408430304, "stop": 1737408430543}], "start": 1737408430304, "stop": 1737408430604}